package net.b07z.sepia.server.assist.interviews;

import java.util.List;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import net.b07z.sepia.server.assist.interpreters.NluResult;
import net.b07z.sepia.server.assist.server.ConfigServices;
import net.b07z.sepia.server.assist.services.ServiceInterface;
import net.b07z.sepia.server.assist.services.ServiceResult;
import net.b07z.sepia.server.core.tools.JSON;

/**
 * Switch from one service result to another.
 * 
 * @author Florian Quirin
 *
 */
public class ConvertResult {
	
	//TODO: we probably need to add a method here that fixes conflicts between the serviceResult expected by Interview
	//and the one generated by "getResult" within an incompatible service (the redirect should happen on Interview level)
	
	/**
	 * Convert the {@link ServiceResult} from one service to another. Both services must support the new standard!
	 * Supports one parameter transfer, if you need more or more complex changes you should edit the {@link NluResult}
	 * in advance. 
	 * @param cmd - target command that determines the service
	 * @param nluResult - result of old service
	 * @param oldParameter - old parameter to be replaced
	 * @param newParameter - new parameter for the new service
	 * @param newValue - new value of the new parameter, can be the old one or a modified version
	 */
	public static ServiceResult switchService(String cmd, NluResult nluResult, 
							String oldParameter, String newParameter, String newValue){
		//rewrite NLU_Result
		nluResult.setParameter(newParameter, newValue);
		nluResult.removeParameter(oldParameter);
		
		List<ServiceInterface> services = ConfigServices.getCustomOrSystemServices(nluResult.input, nluResult.input.user, cmd);
		//this should not be the case here but to be sure ...
		if (services == null || services.isEmpty()){
			return NoResult.get(nluResult);
		}
		//re-do the "interview"
		InterviewInterface interview = new AbstractInterview();
		interview.setCommand(cmd);
		interview.setServices(services);
		InterviewResult iResult = interview.getMissingParameters(nluResult);
		ServiceResult sr;
		if (iResult.isComplete()){
			sr = interview.getServiceResults(iResult);
		}else{
			sr = iResult.getApiComment();
		}
		sr.getServiceInfo().setIntendedCommand(cmd); 	//we need to make sure this is set so the InterviewInterface can adapt to command changes! 
		return sr;
	}
	
	/**
	 * Overwrite answer parameters.
	 * @param sr - given {@link ServiceResult}
	 * @param newAnswerParameters - new answer parameters as JSONObject (or null)
	 * @param parametersToRemove - array of parameters to remove (or null)
	 * @return modified {@link ServiceResult}
	 */
	public static ServiceResult adjustAnswerParameters(ServiceResult sr, JSONObject newAnswerParameters, JSONArray parametersToRemove){
		JSONObject ri = sr.getResultInfo();
		if (parametersToRemove != null){
			JSON.forEach(parametersToRemove, v -> {
				ri.remove(v);
			});
		}
		if (newAnswerParameters != null){
			JSON.forEach(newAnswerParameters, (k, v) -> {
				JSON.put(ri, k, v);
			});
		}
		return sr;
	}

}
